version: "3.8"

services: 
    database:
        image: postgres
        volumes: 
            - ./data:/var/lib/postgresql/data
        # ports: 
            # - "5432:5432"            
        expose: 
            - "5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: apreifsteck_dev
            PG_DATA: /data
    
    backend:
        links: 
            - "database:db"
        build:
            context: .
            dockerfile: Dockerfile.backend
        depends_on: 
            - database 
        ports:
            - "4000:4000"


